- name: Playbook for launching ec2 instances
  hosts: localhost
  vars_prompt:
    - name: count
      prompt: "Number of backend webserver instances: "
      private: no

  vars_files:
    - keys.yml

  tasks:
    - name: Installing required python library
      pip:
        name: boto
        state: present

    - name: Get instance private ip
      command: aws ec2 describe-instances --region ap-south-1 --filter Name=tag:Name,Values="loadbalancer" --query "Reservations[].Instances[].PrivateIpAddress" --output text
      register: instance_ip


    - name: Launching webserver instances
      ec2:
        image: ami-010aff33ed5991201
        instance_type: t2.micro
        count: "{{ count }}"
        region: ap-south-1
        group_id: sg-0e12050f37dafa0bd
        instance_tags:
          Name: "webserver"
        key_name: Ansible
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        wait: yes

    - name: Launching loadbalancer instance
      ec2:
        image: ami-010aff33ed5991201
        instance_type: t2.micro
        region: ap-south-1
        group_id: sg-0e12050f37dafa0bd
        instance_tags:
          Name: "loadbalancer"
        key_name: Ansible
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        wait: yes
      when: instance_ip.stdout == ''
